const pool = require('./db'); 
console.log(process.env.DATABASE_URL);

const createTables = async () => {
  try {
    await pool.query(`
      create table if not exists public.schools (
        id integer generated by default as identity not null,
        schoolname text not null,
        fields text null,
        emailaddress text null,
        constraint schools_pkey primary key (id)
      );
    `);

    await pool.query(`
      create table if not exists public.searches (
        id bigint generated by default as identity not null,
        searchdate timestamp with time zone not null default now(),
        searchname text null,
        field text null,
        countstudents integer null,
        searchername text null,
        classes text null,
        searcherid text null,
        constraint searches_pkey primary key (id)
      );
    `);

    await pool.query(`
      create table if not exists public.staff (
        id text not null,
        schoolid integer not null,
        name text null,
        confirm integer null,
        class text null,
        constraint staff_pkey primary key (id, schoolid),
        constraint staff_schoolid_fkey foreign key (schoolid) references schools (id)
      );
    `);

    await pool.query(`
      create table if not exists public.students (
        id bigint not null,
        firstname text not null,
        lastname text null,
        field1 text null,
        field2 text null,
        field3 text null,
        field4 text null,
        severalpriority integer null default 8,
        field1priority integer null default 1,
        field2priority integer null default 1,
        field3priority integer null default 1,
        field4priority integer null default 1,
        grade integer null,
        class text null,
        schoolid integer not null,
        educpriority boolean null default false,
        constraint students_pkey primary key (id, schoolid),
        constraint students_schoolid_fkey foreign key (schoolid) references schools (id)
      );
    `);

    await pool.query(`
      create table if not exists public.studentsinsearches (
        id integer generated by default as identity not null,
        searchid bigint null,
        studentid bigint null,
        constraint studentsinsearches_pkey primary key (id),
        constraint studentsinsearches_searchid_fkey foreign key (searchid) references searches (id)
      );
    `);

    console.log("✔ כל הטבלאות נוצרו בהצלחה");
  } catch (err) {
    console.error("❌ שגיאה ביצירת הטבלאות:", err);
  } finally {
    pool.end();
  }
};

createTables();
